<?php
/** @var Magento\Framework\View\Element\Template $block */

/** @var $viewModel Palamarchuk\StoreLocator\ViewModel\ModuleConfigViewModel */
$moduleConfigViewModel = $block->getModuleConfigViewModel();
?>
<?php if ($moduleConfigViewModel->moduleIsEnabled()): ?>
    <?php echo $block->getChildHtml('all-store-locations-info'); ?>
<?php else: ?>
    <?php echo $block->getChildHtml('all-not-found-page'); ?>
<?php endif; ?>
