<?php
/** @var Magento\Checkout\Block\Onepage\Success $block */
/** @var $moduleConfigViewModel Palamarchuk\TgOrderNotificationBot\ViewModel\ModuleConfigViewModel */
$moduleConfigViewModel = $block->getModuleConfigViewModel();
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()) : ?>
        <?php if ($block->getCanViewOrder()) : ?>
            <p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php else : ?>
            <p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif; ?>
        <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
        <?php if ((bool)$moduleConfigViewModel->moduleIsEnabled() && (bool)$moduleConfigViewModel->checkHookIsSet() && (bool)$moduleConfigViewModel->getBotName()):
            echo $block->escapeHtml(__('You can check your order status in our telegram bot '));
           echo "<a href='https://telegram.me/" . $moduleConfigViewModel->getBotName()."' >"  .
            $block->escapeUrl('https://telegram.me/' . $moduleConfigViewModel->getBotName()). "</a>"
            ;
        endif; ?>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue"
               href="<?= $block->escapeUrl($block->getContinueUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>
