<?php
/** @var Magento\Framework\View\Element\Template $block */

/** @var $moduleConfigViewModel Palamarchuk\TgOrderNotificationBot\ViewModel\ModuleConfigViewModel */
$moduleConfigViewModel = $block->getModuleConfigViewModel();
?>

<style>
    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
    input[type=submit].delete {
        width: 100%;
        background-color: orangered;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    input[type=submit]:hover {
        background-color: #45a049;
    }
    input[type=submit].delete:hover {
        background-color: darkorchid;
    }

    div.botform {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }
</style>


<div class="botform">
    <form action="#">
        <label for="enable">Enable module</label>
        <select id="enable" name="enable">
            <option value="0" <?php if(!$moduleConfigViewModel->moduleIsEnabled()): echo('selected'); endif; ?>>No</option>
            <option value="1" <?php if($moduleConfigViewModel->moduleIsEnabled()): echo('selected'); endif; ?>>Yes</option>
        </select>

        <label for="bot_name">Bot name (some_name_bot with a _bot postfix)</label>
        <input type="text" id="bot_name" name="bot_name" placeholder="some_name_bot"
               value="<?=$moduleConfigViewModel->getBotName()?>"
        >

        <label for="token">Access token</label>
        <input type="text" id="token" name="token" placeholder="Your access token (without bot word)"
               value="<?=$moduleConfigViewModel->getAccessToken()?>"
        >

        <label for="hook">Hook ( <b>https://{your domain}/tgbot/bot</b> for instant message handling or <b>https://{your domain}/tg_bot/publishmessage/tgbotpublish</b> for queued via RabbitMQ message handling, or any other request catcher for local development )</label>
        <input type="text" id="hook" name="hook" placeholder="Your hook site"
        value="<?=$moduleConfigViewModel->getHook()?>"
        >
        <?php if($moduleConfigViewModel->checkHookIsSet()): echo('<h3 style="color:indianred">Hook is already set</h3>'); endif; ?>

        <input type="submit" value="Submit">
    </form>

</div>
<div class="botform">
    <form action="#">

        <?php if($moduleConfigViewModel->checkHookIsSet()):?>
            <input type="hidden" id="delete" name="delete" value="1" >
            <input type="hidden" id="token" name="token"
                   value="<?=$moduleConfigViewModel->getAccessToken()?>"
            >
            <input type="submit" class="delete" value="Delete">
        <?php endif; ?>
    </form>

</div>



